os: linux
dist: focal
language: node_js
node_js: 'node'

git:
  depth: false

cache:
  npm: true
  yarn: true
  directories:
    - "$HOME/.cache/electron"

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
        key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - jq
      - yarn

script:
  - script/travis-ci.sh

deploy:
  provider: releases
  edge: true
  on:
    repo: Rocket1184/electron-netease-cloud-music
    tags: true
  file: build/*.asar
